#!/bin/sh

echo "nextOS initramfs starting..."

mount -t proc none /proc || echo "Failed to mount /proc"
mount -t sysfs none /sys || echo "Failed to mount /sys"
mount -t devtmpfs none /dev || echo "Failed to mount /dev"


# Create essential devices if missing
[ -e /dev/console ] || mkdir /dev/console c 5 1
[ -e /def/null ] || mkdie /dev/null c 1 3

echo "Initramfs environment ready"
echo "Dropping to shell..."

exec /bin/sh
